language: ruby
before_install: gem install bundler
script: ./build.sh
branches:
  only:
  - master
rvm:
- 2.1.2
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
    secure: Syp5IdRPKVosmaQ2kSkRJsrRLySZaAwDjKddILkC5ndORuZEmVmjGcCbcM/5tZ9RXQDff0Io96JqVydboclbh5eXCRZ+VVuzsWyNzlehzl0VnFaNfpeBO5sVJspdKuFL45gwWeqg9r8kGH1IMpvEgN8QrS5z72PaNhhYWwKFPMDzNVfW8PEocn2zrXIgknHS60PoH8axQie4gMS7OA0fwsn/2hcqWSZqoqONZO7JCxEFDtJXAgRfg+nZ3Apxq1qKV3fUathiaXe3An5ae2HB+gf63smoTIMa15CGs/TKw3u+kZdVGYwtfv0D7Sr3bXnt4uStwy5XgOgrQAC5g+Bqx6moMV9lah+yNkehvp4ItG0pFjxIQWNF6vBYINIHSAo3J7OwQl0czkJUXB5Y4tcdIj5lfqonSNf/ZjG4f/MhQpXwVNIM0loQNIOdWIHvwZoK5q0zK5Fod0YgwJz1ZHqP2PIedNF0MmqxpRWV1rN/ouXcizdiYTDTjLFJihS0EjGKGz+71qA6YoMUtTuS3hTJWwGkJXmLeoXra7u5FC0mBhBFVCeksOa34M6d4aPhx0uHmtyEalzxU20+SbAq0zr8iL3iq5tGncdM19y9MxHE6XF7w3BO2mlzKuKFv+i6KATi0edC8Ye6HVE6mB9KQ0ToSVb+KrT09abwbqSqtUY+YcI=